from .ammonia import AmmoniaSector
from .aviation import AviationSector
from .carbon import CarbonSector
from .cement import CementSector
from .district_heating import DistrictHeatingSector
from .electricity import ElectricitySector
from .gas import GasSector
from .heat import HeatSector
from .hydrogen import HydrogenSector
from .methanol import MethanolSector
from .passenger_transport import PassengerTransportSector
from .refining import RefiningSector
from .shipping import ShippingSector
from .steel import SteelSector
from .truck_transport import TruckTransportSector
